name: moyo
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.8.1







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.0
  awesome_snackbar_content: ^0.1.7
  getwidget: ^7.0.0
  lottie: ^3.3.1
  dio: ^5.9.0
  animations: ^2.0.11
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/heart.png"
  min_sdk_android: 21





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
